apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: url-shortener
type: Opaque
stringData:
  POSTGRES_PASSWORD: "123456"  # Replace with actual password or use `kubectl create secret`
